### ISSUE TITLE
Setting a backup path will only set if it is a directory, but it is used as a file path in backupPhar()

### ISSUE THREAD

**Issue by frak** [padraic/phar-updater#2]
When you try to setup a different backup path using the documented [setBackupPath() ](https://github.com/padraic/phar-updater/blob/master/src/Updater.php#L259) it goes to great lengths to ensure it is a directory.  However, if you try to update the phar it is assumed in [getBackupPharFile()](https://github.com/padraic/phar-updater/blob/master/src/Updater.php#L433) that the backup path is actually to a file.  When you then try and run the command it fails on line 364 of Updater.php because you cannot copy a file to a directory [in that way](http://php.net/manual/en/function.copy.php#45357).

**Comment by padraic** [comment]
This is true. I just wrapped up some Humbug work (new phar build). I'll be back on phar-updater to firm up the rollback and Github Releases support tomorrow. So this will get fixed then.

Thanks for trying it out though! Hopefully I can put out a stable first release shortly.

**Comment by frak** [comment]
Thanks for writing such a handy tool - I look forward to the fix :o)
